name: ci

# This workflow builds manylinux torchlib wheels as they will appear
# in the production environment. The challenging part is to create
# environment to properly build torchcodec which must be able to work
# in environments with different versions of FFmpeg. We handle that by
# pre-building few torchcodec op DLLs against few versions of FFmpeg.
#
# We could use quay.io/pypa/manylinux_2_28_x86_64 container instead
# of the pytorch container in all the jobs. However, with PyPa container
# we would need to setup Intel driver stack ourselves while pytorch
# container handles this for us though it weighs more.

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'
  release:
    types:
      - published      

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PR_OR_SHA: ${{ github.event.pull_request.number || github.sha }}
  UNIQUE_ID: ${{ github.run_id }}

jobs:
  # This job builds few bare minimal versions of FFmpeg with all
  # features disabled. We use the produced artifacts later building
  # torchcodec. At runtime we use other FFmpeg versions from Ubuntu
  # or Conda.
  ffmpeg:
    strategy:
      matrix:
        ffmpeg-version: [ 'n6.1.4', 'n7.1.3', 'n8.0.1', 'n9.0.1' ]
    runs-on: ubuntu-24.04
    container:
      image: 'quay.io/pypa/manylinux_2_28_x86_64'
    env:
      PREFIX: ${{ github.workspace }}/_install/ffmpeg-${{ matrix.ffmpeg-version }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v7
      with:
        repository: FFmpeg/FFmpeg
        ref: ${{ matrix.ffmpeg-version }}
    - name: 'Install prerequisites'
      run: |
        dnf config-manager --set-enabled powertools  # for nasm
        dnf install -y nasm
    - name: 'Configure FFmpeg'
      run: |
        ./configure \
          --prefix="$PREFIX" \
          --libdir="$PREFIX/lib" \
          --disable-everything \
          --disable-static \
          --disable-doc \
          --enable-shared
    - name: 'Build and install FFmpeg'
      run: |
        make -j$(nproc) && make install
    - name: 'Verify FFmpeg'
      working-directory: ${{ env.PREFIX }}
      env:
        LD_LIBRARY_PATH: ${{ env.PREFIX }}/lib
      run: |
        ./bin/ffmpeg -version
    - name: 'Upload FFmpeg'
      uses: actions/upload-artifact@v7
      with:
        name: ffmpeg-${{ matrix.ffmpeg-version }}
        path: _install

  build:
    needs: ffmpeg
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
    runs-on: ubuntu-24.04
    env:
      WHEELS: torchlib-${{ matrix.python-version }}-wheels
    container:
      image: 'pytorch/manylinux2_28-builder:xpu-v2.13.0-rc1'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v7
    - name: 'Download FFmpeg'
      uses: actions/download-artifact@v8
      with:
        path: ${{ github.workspace }}/_install
        # The goal is to get the following layout:
        # _install/
        #   ffmpeg-x
        #   ffmpeg-y
        merge-multiple: true
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: 'Install prerequisites'
      run: |
        rpm --import https://repositories.intel.com/gpu/intel-graphics.key
        dnf install -y libva-devel
    - name: 'Build the project'
      env:
        TORCHCODEC_FFMPEG6_INSTALL_PREFIX: ${{ github.workspace }}/_install/ffmpeg-n6.1.4
        TORCHCODEC_FFMPEG7_INSTALL_PREFIX: ${{ github.workspace }}/_install/ffmpeg-n7.1.3
        TORCHCODEC_FFMPEG8_INSTALL_PREFIX: ${{ github.workspace }}/_install/ffmpeg-n8.0.1
        TORCHCODEC_FFMPEG9_INSTALL_PREFIX: ${{ github.workspace }}/_install/ffmpeg-n9.0.1
      run: |
        source /opt/intel/oneapi/setvars.sh
        uv build --all --index https://download.pytorch.org/whl/xpu -vv
    - name: 'Repair wheels with auditwheel'
      run: |
        uvx auditwheel repair dist/*.whl \
          --wheel-dir _wheels/${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }} \
          --exclude "*" --allow-pure-python-wheel
    - name: 'Test installing wheels'
      run: |
        uv venv
        uv pip install \
          _wheels/${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}/*.whl \
          --index https://download.pytorch.org/whl/xpu -vv
    - name: 'Upload wheels'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}
        path: _wheels
        compression-level: 0

  # This job just merges all wheels into single archive
  compose:
    needs: build
    runs-on: ubuntu-24.04
    env:
      WHEELS: torchlib-all-wheels
    steps:
    - name: 'Download wheels'
      uses: actions/download-artifact@v8
      with:
        pattern: torchlib-*
        path: _all_wheels
        # The goal is to get the following layout:
        # _all_wheels/
        #   torchlib-3.14-wheels-xxx-yyy
        #   torchlib-3.13-wheels-xxx-yyy
        merge-multiple: true
    - name: 'Install prerequisites'
      run: |
        sudo apt-get update
        sudo apt-get install -y tree
    - name: 'List downloads'
      run: |
        tree _all_wheels/
    - name: 'Form uploads'
      run: |
        TO=${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}
        mkdir _wheels && mkdir _wheels/$TO
        find _all_wheels/ -name "*-cp[0-9]*-cp[0-9]*-*.whl" \
          -exec cp {} _wheels/$TO \;
        # Take "*-none-any.whl" from the oldest python we've built for
        find "$(ls -d _all_wheels/*/ | sort | head -n 1)" -name "*-none-any.whl" \
          -exec cp {} _wheels/$TO \;
    - name: 'List uploads'
      run: |
        tree _wheels/
    - name: 'Upload wheels'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}
        path: _wheels/
        compression-level: 0

  identify-changes:
    runs-on: ubuntu-24.04
    outputs:
      torchcodec-xpu: ${{ case(github.event_name == 'release', 'true',
                            github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'test-all'), 'true',
                            steps.changes.outputs.torchcodec-xpu || 'false') }}
      fbgemm-xpu: ${{ case(github.event_name == 'release', 'true',
                        github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'test-all'), 'true',
                        steps.changes.outputs.fbgemm-xpu || 'false') }}
    steps:
      - name: 'Checkout'
        if: github.event_name != 'release'
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: 'Identify changes'
        if: github.event_name != 'release'
        uses: dorny/paths-filter@v4
        id: changes
        with:
          base: ${{ github.event.before || 'HEAD~1' }}
          filters: |
            torchcodec-xpu:
              - 'packages/torchcodec-xpu/**'
            fbgemm-xpu:
              - 'packages/fbgemm-xpu/**'

  test-torchcodec:
    needs: [ build, identify-changes ]
    if: needs.identify-changes.outputs.torchcodec-xpu == 'true'
    strategy:
      matrix:
        # Ubuntu 24.04 comes with ffmpeg version 6
        # Ubuntu 26.04 comes with ffmpeg version 8
        image: [ 'ubuntu:24.04', 'ubuntu:26.04' ]
        # Testing in minimum and maximum supported versions of python.
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
        # TODO: re-enable dg2 runner after https://github.com/intel/torchlib-xpu/issues/94
        runner: [ 'bmg', 'dg2' ]
        # Default fallback value for standard matrix combinations
        cpu_fallback: [ false ]  # fallback not allowed
        force_cpu_fallback: [ false ]

        include:
        # This verifies default behavior when CPU fallback is allowed and not forced
        - image: 'ubuntu:26.04'
          python-version: '3.14'
          runner: 'bmg'
          cpu_fallback: true
          force_cpu_fallback: false
        # This verifies forced fallback scenario when decoding is entirely on CPU
        - image: 'ubuntu:26.04'
          python-version: '3.14'
          runner: 'bmg'
          cpu_fallback: true
          force_cpu_fallback: true
    runs-on: ${{matrix.runner}}
    container:
      image: '${{ matrix.image }}'
      options: --device /dev/dri:/dev/dri -v /dev/dri/by-path:/dev/dri/by-path
    env:
      CPU_FALLBACK: ${{ matrix.cpu_fallback == true }}
      FORCE_CPU_FALLBACK: ${{ matrix.force_cpu_fallback == true }}
      TORCHCODEC_XPU_LOG_LEVEL: '3'  # info
      WHEELS: torchlib-${{ matrix.python-version }}-wheels
    steps:
    - name: 'Cleanup'
      run: |
        rm -rf .torchlib-xpu-venv
        rm -rf _wheels
        rm -rf _tools
    - name: 'Set AGENT_TOOLSDIRECTORY'
      run: |
        # For https://github.com/actions/setup-python/issues/1087
        echo "AGENT_TOOLSDIRECTORY=$GITHUB_WORKSPACE/_tools" >> $GITHUB_ENV
    - name: 'Install prerequisites'
      run: |
        apt-get update
        apt-get install -y \
          ca-certificates \
          curl \
          git \
          gpg \
          software-properties-common \
          wget
        git config --global user.email "nobody@intel.com"
        git config --global user.name "Nobody"
    - name: 'Download wheels'
      uses: actions/download-artifact@v8
      with:
        name: ${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}
        path: _wheels/
    - name: 'Checkout torchlib-xpu'
      uses: actions/checkout@v7
      with:
        path: torchlib-xpu
    - name: 'Checkout torchcodec'
      uses: actions/checkout@v7
      with:
        repository: meta-pytorch/torchcodec
        ref: v0.16.0
        path: torchcodec
        clean: true
    - name: 'Patch torchcodec'
      working-directory: torchcodec
      run: |
        rm -rf .git/rebase-apply
        git am ../torchlib-xpu/packages/torchcodec-xpu/patches/0001-Add-XPU-support-to-tests.patch
        git am ../torchlib-xpu/packages/torchcodec-xpu/patches/0002-Add-XPU-support-to-video-encoder-tests.patch
    - name: 'Install FFmpeg and Intel drivers'
      run: |
        add-apt-repository -y ppa:kobuk-team/intel-graphics
        # Uncomment below to install packages available at specific date
        # echo "Snapshot: 20260624T090400Z" >> /etc/apt/sources.list.d/kobuk-team-ubuntu-intel-graphics-noble.sources
        # apt-get update
        apt-get install -y \
          ffmpeg \
          libva2 \
          libze1 \
          libze-intel-gpu1 \
          intel-media-va-driver-non-free \
          intel-opencl-icd \
    - name: 'Print FFmpeg version'
      run: |
        ffmpeg -version
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: 'Create virtual environment'
      run: |
        rm -rf .torchlib-xpu-venv
        python -m venv .torchlib-xpu-venv
        echo "$GITHUB_WORKSPACE/.torchlib-xpu-venv/bin" >> $GITHUB_PATH
    - name: 'Install torchcodec'
      run: |
        find _wheels/ -name "*.whl"
        pip install --no-cache-dir \
          "$(ls ./_wheels/${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}/torchcodec*.whl)[test]" \
          --extra-index-url https://download.pytorch.org/whl/xpu
    - name: 'Test gpu'
      run: |
        python -c "import torch; assert torch.xpu.is_available(), 'XPU (Intel GPU) is not available'"
    - name: 'Test'
      working-directory: torchcodec
      run: |
        if [ "$FORCE_CPU_FALLBACK" = "true" ] || [ "${{ matrix.image }}" = "ubuntu:24.04" ] || [ "${{ matrix.runner }}" = "dg2" ]; then
          # On dg2 see: https://github.com/intel/media-driver/issues/1954
          known_failures="not test_get_frame_at_av1[xpu]"
        fi
        pytest -rsf --capture=no -k "${known_failures}" test/

  test-fbgemm:
    needs: [ build, identify-changes ]
    if: needs.identify-changes.outputs.fbgemm-xpu == 'true'
    strategy:
      matrix:
        # Testing in minimum and maximum supported versions of python.
        python-version: [ '3.10', '3.14' ]
        runner: [ 'bmg' ]
    runs-on: ${{matrix.runner}}
    container:
      image: 'ubuntu:24.04'
      options: --device /dev/dri:/dev/dri -v /dev/dri/by-path:/dev/dri/by-path
    env:
      WHEELS: torchlib-${{ matrix.python-version }}-wheels
    steps:
    - name: 'Cleanup'
      run: |
        rm -rf .torchlib-xpu-venv
        rm -rf _wheels
        rm -rf _tools
    - name: Set AGENT_TOOLSDIRECTORY
      run: |
        # For https://github.com/actions/setup-python/issues/1087
        echo "AGENT_TOOLSDIRECTORY=$GITHUB_WORKSPACE/_tools" >> $GITHUB_ENV
    - name: 'Install prerequisites'
      run: |
        apt-get update
        apt-get install -y \
          ca-certificates \
          curl \
          git \
          gpg \
          software-properties-common \
          wget
        git config --global user.email "nobody@intel.com"
        git config --global user.name "Nobody"
    - name: 'Download wheels'
      uses: actions/download-artifact@v8
      with:
        name: ${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}
        path: _wheels/
    - name: 'Checkout torchlib-xpu'
      uses: actions/checkout@v7
      with:
        path: torchlib-xpu
    - name: 'Checkout fbgemm'
      uses: actions/checkout@v7
      with:
        repository: pytorch/FBGEMM
        ref: v1.8.0
        path: fbgemm
        clean: true
    - name: 'Patch FBGEMM'
      working-directory: fbgemm
      run: |
        rm -rf .git/rebase-apply
        git am ../torchlib-xpu/packages/fbgemm-xpu/patches/0001-Add-XPU-support-to-fbgemm-tests.patch
    - name: 'Install Intel drivers'
      run: |
        add-apt-repository -y ppa:kobuk-team/intel-graphics
        apt-get install -y \
          libze1 \
          libze-intel-gpu1 \
          intel-ocloc
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: 'Create virtual environment'
      run: |
        rm -rf .torchlib-xpu-venv
        python -m venv .torchlib-xpu-venv
        echo "$GITHUB_WORKSPACE/.torchlib-xpu-venv/bin" >> $GITHUB_PATH
    - name: 'Install fbgemm-xpu'
      run: |
        pip install --no-cache-dir \
          "$(ls ./_wheels/${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}/fbgemm_xpu*.whl)[test]" \
          --extra-index-url https://download.pytorch.org/whl/xpu
    - name: 'Test gpu'
      run: |
        python -c "import torch; assert torch.xpu.is_available(), 'XPU (Intel GPU) is not available'"
    - name: 'Test fbgemm-xpu'
      working-directory: fbgemm
      run: |
        pytest -rsf fbgemm_gpu/test/sparse/misc_ops_test.py
        pytest -rsf fbgemm_gpu/test/sparse/permute_sparse_features_test.py
        pytest -rsf fbgemm_gpu/test/sparse/cumsum_test.py
        pytest -rsf fbgemm_gpu/test/sparse/block_bucketize_test.py
        pytest -rsf fbgemm_gpu/test/tbe/utils/generate_vbe_metadata_test.py
        pytest -rsf fbgemm_gpu/test/tbe/utils/split_embeddings_utils_test.py
        pytest -rsf fbgemm_gpu/test/jagged/expand_into_jagged_permute_test.py

  publish:
    needs: [ compose, test-torchcodec, test-fbgemm ]
    if: ${{ !(failure() || cancelled()) }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write    
    env:
      WHEELS: torchlib-all-wheels
    steps:
    - name: 'Download wheels'
      uses: actions/download-artifact@v8
      with:
        name: ${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}
        path: _wheels
    - name: 'List wheels'
      run: |
        tree _wheels/
    - name: 'Prepare wheels'
      run: |
        rm -rf _publish && mkdir _publish
        cp ./_wheels/${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}/torchcodec_xpu-*.whl _publish/
        cp ./_wheels/${{ env.WHEELS }}-${{ env.PR_OR_SHA }}-${{ env.UNIQUE_ID }}/torchlib_xpu-*.whl _publish/
        ls -al _publish/
    - name: Publish package distributions to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: _publish
